layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Terraform
    web_url: https://www.terraform.io/
    image_url: https://www.terraform.io/assets/images/og-image-8b3e4f7d.png

  - name: Ansible
    web_url: https://www.ansible.com/
    image_url: https://www.ansible.com/hubfs/2016_Images/Assets/Ansible-Mark-Large-RGB-Mango.png?hsLang=en-us

  - name: AWS
    web_url: https://aws.amazon.com/jp/
    image_url: https://amazonwebservices.gallerycdn.vsassets.io/extensions/amazonwebservices/aws-vsts-tools/1.1.8/1541109517627/images/logo.png

  - name: GCP
    web_url: https://cloud.google.com/?hl=ja
    image_url: /assets/gcp.png

  - name: Docker
    web_url: https://www.docker.com/
    image_url: https://www.docker.com/sites/default/files/social/docker_facebook_share.png

  - name: Kubernetes
    web_url: https://kubernetes.io/
    image_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
