layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Terraform
    web_url: https://www.terraform.io/
    image_url: https://www.terraform.io/assets/images/og-image-8b3e4f7d.png

  - name: Ansible
    web_url: https://www.ansible.com/
    image_url: https://www.ansible.com/hubfs/2016_Images/Assets/Ansible-Mark-Large-RGB-Mango.png?hsLang=en-us

  - name: AWS
    web_url: https://aws.amazon.com/jp/
    image_url: https://amazonwebservices.gallerycdn.vsassets.io/extensions/amazonwebservices/aws-vsts-tools/1.1.8/1541109517627/images/logo.png
